### ISSUE TITLE
Pin Mapping

### ISSUE THREAD

**Issue by MichaelSmi** [hallard/LoRasPI#5]
Hi Charles,

first thank you very much for creating and sharing your PCB here!

I'd like to use your board (I ordered 8) like a breakout board.
I cant figure out the pin mapping on the left pin column of the LoRasPi 1.2a.
I'd like to connect those pins to an Arduino pro mini.

I made the following pin mapping:

 LoRasPI | RFM65 | Arduino Pro Mini 
------------ | ------------- | -------------
 GND | GND | GND 
 MISO | MISO | MISO
 MOSI | MOSI | MOSI
 3V3 | VCC | VCC
 IO22 | RST | RST
 D0 | DIO 0 | D4
 D1 | DIO 1 | D5
 D2 | DIO 2 | D7
 CE0 | ? | ?
 CS | ? | ?
 CE1 | ? | ?

Is the map correct? Could you please correct any errors on LoRasPI col?

**Comment by hallard** [comment]
You're Arduino don't have CE0/CE1 choice, so you just need to connect CS to SS pin (D10 ?)
