### ISSUE TITLE
OR gate for DIOx

### ISSUE THREAD

**Issue by mrubioroy** [hallard/LoRasPI#7]
On the schematics you show three Zener diodes for the OR logic gate between DIO0, DIO1 and DIO2. Must they be Zener or any other type should do? What are the characteristics needed for those diodes? I'm guessing they should be 3216 size from the PCB dimensions.

Thanks

**Comment by hallard** [comment]
Yeah schematic symbol may not be accurate and should not be Zener diode.
Diode are 1N4148 or Schottky in SOD123 package.
